2020-05-09 16:01:21,136 ERROR: Exception on /followings/david [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Lisa\salon\app\routes.py", line 260, in followings
    prev_url = prev_url)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\follow_ers_ings.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Lisa\salon\app\templates\follow_ers_ings.html", line 17, in block "app_content"
    <a href="{{ url_for('user', username=user.username) }}">
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2020-05-09 16:05:13,259 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 16:05:43,750 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 17:17:16,354 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 17:34:26,518 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:05:57,100 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:06:34,078 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:16:24,288 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:23:19,887 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:33:22,576 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:43:48,802 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 18:57:33,587 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 19:01:52,249 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:16:15,353 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:16:28,055 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:18:59,320 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:21:13,963 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:26:44,420 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:32:39,768 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:34:59,248 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:36:06,859 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:39:22,588 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 21:42:02,433 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:04:33,745 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:04:55,285 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:09:48,721 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:10:41,698 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:14:12,913 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:19:32,285 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:20:01,513 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:20:28,041 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:21:00,670 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:24:29,390 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:24:59,795 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:25:01,436 ERROR: Exception on / [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Lisa\salon\app\routes.py", line 39, in index
    next_url = next_url, prev_url = prev_url)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Lisa\salon\app\templates\index.html", line 8, in block "app_content"
    {% include '_master.html' %}
  File "C:\Users\Lisa\salon\app\templates\_master.html", line 6, in top-level template code
    <img src="{{ users[master.user_id|int -1].avatar(110) }}" />
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: list object has no element 6
2020-05-09 22:26:48,359 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
